#include<stdio.h>
void main()
{
	int mat[4][4]={2,3,4,8,1,6,7,12,5,10,11,16,9,13,14,15},r,c,shift,temp,d,de;
	printf("Before shifting \n");
	for(r=0;r<4;r++)
	{
		for(c=0;c<4;c++)
		{
			printf("%4d",mat[r][c]);
		}
		printf("\n");
	}
	shift=mat[1][0];
	for(c=0;c<3;c++)
	{
		temp=mat[0][c];
		mat[0][c]=shift;
		shift=temp;
	}
	for(r=0;r<3;r++)
	{
		temp=mat[r][3];
		mat[r][3]=shift;
		shift=temp;
	}
	for(c=3;c>0;c--)
	{
		temp=mat[3][c];
		mat[3][c]=shift;
		shift=temp;
	}
	for(r=3;r>0;r--)
	{
		temp=mat[r][0];
		mat[r][0]=shift;
		shift=temp;
	}
	printf("After shifting \n");
	for(r=0;r<4;r++)
	{
		for(c=0;c<4;c++)
		{
			printf("%4d",mat[r][c]);
			/*for(d=1;d<=50000;d++)
            {
                for(de=1;de<=5000;de++);
            }*/
		}
		printf("\n");
	}
	getch();
}
