#include<stdio.h>
#include<conio.h>
void main()
{
    int num=12345,numcopy=num,arr[10],len=0,es=NULL,l,d,i,pass;
    for(;num>0;num=num/10)
    {
        len=len+1;
        d=num%10;
        if(d%2==0)
        {
            if(d<es)
                es=d;
        }
    }
    num=numcopy;
    printf("%d\n",es);
    i=0;
    for(l=0;l<len;l++)
    {
        d=num%10;
        if(d%2==1)
        {
            arr[i]=d;
            i++;
        }
        if(d%2==0)
        {
            if(d!=es)
            {
                arr[i]=d;
                i++;
            }
        }
        num=num/10;
    }
    for(i=0;i<len-1;i++)
    {
        printf("%5d",arr[i]);
    }
    printf("\n");
    int ri=i,p,small,sp,temp;
    for(pass=0;pass<len-1;pass++)
    {
        small=arr[pass];
        for(p=pass;p<len-1;p++)
        {
            if(arr[p]>=small)
            {
                small=arr[p];
                sp=p;
            }
        }
        temp=arr[sp];
        arr[sp]=arr[pass];
        arr[pass]=temp;
    }
    for(i=0;i<len-1;i++)
    {
        printf("%5d",arr[i]);
    }
    printf("\n");
    for(i=0;i<len-1;i++)
    {
        d=arr[i];
        num=num*10+d;
    }
    num=num*10+es;
    printf("%d\n",num);
}
