#include<conio.h>
#include<stdio.h>
void main()
{
    int l,len=40,h,hig=17,d,de;
    for(l=1;l<=len;l++)
    {
        printf("C");
        for(d=1;d<=50000;d++)
        {
            for(de=1;de<=500;de++);
        }
    }
    for(h=1;h<=hig-2;h++)
    {
        printf("\nC");
        for(d=1;d<=50000;d++)
        {
            for(de=1;de<=500;de++);
        }
    }
    printf("\n");
    for(l=1;l<=len;l++)
    {
        printf("C");
        for(d=1;d<=50000;d++)
        {
            for(de=1;de<=500;de++);
        }
    }
    getch();
}
