#include<stdio.h>
#include<math.h>
void main()
{
    int i,j,f,a,c,l,b;
    for(i=2;i<100;i++)
    {
        f=0;
        for(j=2;j<i;j++)
        {
            if(i%j==0)
                f=1;
        }
        if(f==0)
        {
            //printf("%7d",i);
            a=i;
            c=0;
            for(;a>0;a=a/10)
                c++;
            printf("%7d",c);
            b=0;
            a=0;
            l=i;
            while(a<c)
            {
                l=((pow(10,c-1))*(l%10))+(l/10);
                //printf("%10d\n",l);
                a++;
                f=0;
                for(j=2;j<i;j++)
                {
                    if(l%j==0)
                        f=1;
                }
                if(f==0)
                    b++;
            }
            printf("%7d",b);
            if(b==c)
            {
                l=i;
                while(b>0)
                {
                    printf("%7d",l);
                    l=pow(10,c-1)*(l%10)+(l/10);
                    b--;
                }
                printf("\n");
            }
            printf("\n");
        }
    }
}
