#include<conio.h>
#include<stdio.h>
void main()
{
    int l,h,len=17,hig=21,d,de;
    for(l=1;l<=len;l++)
    {
        printf("E");
        for(d=1;d<=50000;d++)
        {
            for(de=1;de<=500;de++);
        }
    }
    for(h=1;h<=(hig-3)/2;h++)
    {
        printf("\nE");
        for(d=1;d<=50000;d++)
        {
            for(de=1;de<=500;de++);
        }
    }
    printf("\n");
    for(l=1;l<=len;l++)
    {
        printf("E");
        for(d=1;d<=50000;d++)
        {
            for(de=1;de<=500;de++);
        }
    }
    for(h=1;h<=(hig-3)/2;h++)
    {
        printf("\nE");
        for(d=1;d<=50000;d++)
        {
            for(de=1;de<=500;de++);
        }
    }
    printf("\n");
    for(l=1;l<=len;l++)
    {
        printf("E");
        for(d=1;d<=50000;d++)
        {
            for(de=1;de<=500;de++);
        }
    }
    getch();
}
